<a href="https://colab.research.google.com/github/JuanMunoz20/SQL-Biblioteca2/blob/main/Laboratorio_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = { "nombre" : ["Ana", "Carlos", "Beatriz", "Daniel", "Elena", "Fernando","Gabriela", "Hugo"], "Profesion" : ["Ingenieria", "Medico,", "Abogado", "Arquitecto", " Diseñador", " Programador", "Maestra", "Chef"], "Pais" : ["Mexico", "Argentina", "Brasil", "Chile", "España", "Peru", "Colombia", "Uruguay"] }
df = pd.DataFrame(data)
print(df)

     nombre     Profesion       Pais
0       Ana    Ingenieria     Mexico
1    Carlos       Medico,  Argentina
2   Beatriz       Abogado     Brasil
3    Daniel    Arquitecto      Chile
4     Elena     Diseñador     España
5  Fernando   Programador       Peru
6  Gabriela       Maestra   Colombia
7      Hugo          Chef    Uruguay


In [ ]:
import pandas as pd
df = pd.read_csv("data.csv")
print(df)

     Duracion  Pulso  Maxpulso  Calorias
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


In [ ]:
df_json = pd.read_json("data.json")
print(df_json)


     Duracion  Pulso  Maxpulso  Calorias
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


In [ ]:
df.head(20)

Duracion  Pulso  Maxpulso  Calorias
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0
15        60     98       120     215.2
16        60    100       120     300.0
17        45     90       112       NaN
18        60    103       123     323.0
19        45     97       125     243.0

In [ ]:
df_json.columns

Index(['Duracion', 'Pulso', 'Maxpulso', 'Calorias'], dtype='object')

In [ ]:
df.dtypes

Duracion      int64
Pulso         int64
Maxpulso      int64
Calorias    float64
dtype: object

In [ ]:
df_json.describe()

Duracion       Pulso    Maxpulso     Calorias
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.800000
std     42.299949   14.510259   16.450434   266.377134
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [14]:
import numpy as np
num_fila = 10
num_columna = 5
array_random = np.random.rand(num_fila, num_columna)
print (array_random)

[[0.2978349  0.5912463  0.18904966 0.89274991 0.82259568]
 [0.62116491 0.07655787 0.12054503 0.71691708 0.11596655]
 [0.2305519  0.2484237  0.25088303 0.28395312 0.09738607]
 [0.63834645 0.6232261  0.06382604 0.41877981 0.53862669]
 [0.91859572 0.20821181 0.33933841 0.43055637 0.63487451]
 [0.14635028 0.78791376 0.53030977 0.84196729 0.02230786]
 [0.79744872 0.16124823 0.21882907 0.84121094 0.22958381]
 [0.29554999 0.22729051 0.21361144 0.8150075  0.43966294]
 [0.47544966 0.3433385  0.57002364 0.13736569 0.16398926]
 [0.68622513 0.11200027 0.14410277 0.66161085 0.37271799]]


In [17]:
import numpy as np

# Crear un array de números del 1 al 10
array = np.arange(1, 11)

# Calcular la suma, la media y el valor máximo
suma = np.sum(array)
media = np.mean(array)
maximo = np.max(array)

# Imprimir los resultados
print("Suma:", suma)
print("Media:", media)
print("Valor máximo:", maximo)

Suma: 55
Media: 5.5
Valor máximo: 10


In [18]:
import numpy as np

# Crear un array de 3x4 lleno de ceros
array_zeros = np.zeros((3, 4))

# Cambiar la forma del array a 2x6
array_reshape = array_zeros.reshape(2, 6)

# Imprimir el array con la nueva forma
print(array_reshape)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [19]:
import numpy as np

# Generar una matriz aleatoria de 3x3
matriz_aleatoria = np.random.rand(3, 3)

# Calcular la transpuesta
matriz_transpuesta = matriz_aleatoria.T

# Imprimir la matriz original y la transpuesta
print("Matriz original:")
print(matriz_aleatoria)
print("\nMatriz transpuesta:")
print(matriz_transpuesta)

Matriz original:
[[0.14855121 0.34764961 0.60080318]
 [0.05623111 0.6664762  0.63731081]
 [0.6712018  0.31899181 0.79235322]]

Matriz transpuesta:
[[0.14855121 0.05623111 0.6712018 ]
 [0.34764961 0.6664762  0.31899181]
 [0.60080318 0.63731081 0.79235322]]


In [20]:
import numpy as np

# Crear dos arrays con 5 valores cada uno
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Concatenar los arrays
array_concatenado = np.concatenate((array1, array2))

# Imprimir el array concatenado
print(array_concatenado)

[ 1  2  3  4  5  6  7  8  9 10]
